server:
  port: 21409
  servlet:
    context-path: /
    session:
      timeout: 600s

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orbis
    username: s312693
    password: uuh591
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings